version: '3'

services:
  db:
    image: mariadb:5.5.60
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  adminer:
    image: adminer
    ports:
      - "9090:8080"
  api:
    build:
      context: .
      dockerfile: php_apache.Dockerfile
    env_file:
      - "./.env_api"
    ports:
      - "8088:80"
    volumes:
      - "./apache.conf:/etc/apache2/sites-available/000-default.conf"
  frontend_app:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - "./.env_front"