version: '3'

services:
  api:
    volumes:
      - "./src/php-profile-rest-api:/var/www/html"
  frontend_app:
    volumes:
      - ./src/node_simple_static_server:/app
    entrypoint:
      - "npm"
      - "run"
      - "dev"
